-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 20:49:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecomerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecomerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecomerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecomerce` ;

-- -----------------------------------------------------
-- Table `ecomerce`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`usuarios` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombreusuario` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `contraseña` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `apellido` VARCHAR(20) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `creado_a_las` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `nombreusuario` (`nombreusuario` ASC) VISIBLE,
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`carrito_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`carrito_compras` (
  `carrito_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `creado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`carrito_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `carrito_compras_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecomerce`.`usuarios` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`categorias` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`direccion` (
  `direccion_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `barrio` VARCHAR(255) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`direccion_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `direccion_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecomerce`.`usuarios` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`orden` (
  `orden_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `direccion_envio_id` INT NULL DEFAULT NULL,
  `direccion_facturacion_id` INT NULL DEFAULT NULL,
  `monto_total` DECIMAL(10,2) NOT NULL,
  `status` ENUM('pendiente', 'pagada', 'enviada', 'cancelada') NULL DEFAULT 'pendiente',
  `creado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`orden_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `direccion_envio_id` (`direccion_envio_id` ASC) VISIBLE,
  INDEX `direccion_facturacion_id` (`direccion_facturacion_id` ASC) VISIBLE,
  CONSTRAINT `orden_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecomerce`.`usuarios` (`user_id`),
  CONSTRAINT `orden_ibfk_2`
    FOREIGN KEY (`direccion_envio_id`)
    REFERENCES `ecomerce`.`direccion` (`direccion_id`),
  CONSTRAINT `orden_ibfk_3`
    FOREIGN KEY (`direccion_facturacion_id`)
    REFERENCES `ecomerce`.`direccion` (`direccion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`productos` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `cantidad` INT NOT NULL,
  `imagen_url` VARCHAR(255) NULL DEFAULT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  `creado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`producto_id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ecomerce`.`categorias` (`categoria_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`orden_objetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`orden_objetos` (
  `orden_objetos_id` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `precio_en_orden` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`orden_objetos_id`),
  INDEX `orden_id` (`orden_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `orden_objetos_ibfk_1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `ecomerce`.`orden` (`orden_id`)
    ON DELETE CASCADE,
  CONSTRAINT `orden_objetos_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ecomerce`.`productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`pagos` (
  `pagos_id` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NULL DEFAULT NULL,
  `metodo_pago` ENUM('tarjeta_credito', 'paypal', 'transferencia_bancaria') NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `estado_de_pago` ENUM('pendiente', 'aprobado', 'fallido') NULL DEFAULT 'pendiente',
  `fecha_de_pago` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pagos_id`),
  INDEX `orden_id` (`orden_id` ASC) VISIBLE,
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `ecomerce`.`orden` (`orden_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecomerce`.`producto_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecomerce`.`producto_carrito` (
  `producto_carrito_id` INT NOT NULL AUTO_INCREMENT,
  `carrito_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `precio_adicion` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`producto_carrito_id`),
  INDEX `carrito_id` (`carrito_id` ASC) VISIBLE,
  INDEX `producto_id` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `producto_carrito_ibfk_1`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `ecomerce`.`carrito_compras` (`carrito_id`)
    ON DELETE CASCADE,
  CONSTRAINT `producto_carrito_ibfk_2`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ecomerce`.`productos` (`producto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
